version: '3.7'
services:
  minio-server:
    image: minio/minio:RELEASE.2024-04-06T05-26-02Z-cpuv1
    user: 1000:1000
    ports:
        - 9090:9000
        - 8080:8080
    environment: 
        - MINIO_ROOT_USER=minioadminn
        - MINIO_ROOT_PASSWORD=minioadminn
        # - MINIO_DEFAULT_BUCKETS=
    volumes:
        - ./data-minio:/export
    command: server /export --console-address 0.0.0.0:8080

  createbuckets:
    image: minio/mc
    depends_on:
      - minio-server
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio-server:9000 minioadminn minioadminn;
      /usr/bin/mc rm -r --force myminio/mybucket;
      /usr/bin/mc mb myminio/mybucket;
      /usr/bin/mc policy download myminio/mybucket;
      exit 0;"
