version: '3.7'
services:
  postgres-server:
    image: postgres:16.3-alpine
    ports:
    - 5432:5432
    stop_grace_period: 1m
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=password
