version: '3.7'
services:
  redis-server:
    image: redis:7.2.4-alpine
    ports:
    - 6379:6379
    stop_grace_period: 1m
    environment:
    - ALLOW_EMPTY_PASSWORD=yes
    # command: ["redis-server", "--requirepass", "changeme"]     # REDISDSN=redis://redis:changeme@redis-server:6379/0
